# Generated by Django 5.0 on 2025-12-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_es_alcoholico'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
