# Generated by Django 5.0 on 2025-12-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_stock_producto_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
