"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path
from decouple import config
from urllib.parse import urlparse, parse_qs

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-%e6dtf^r3hzfl4otgh9d+r^7tb2*08aqsr)y6s=^ks+$ht!-#&')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

default_hosts = 'localhost,127.0.0.1,*.render.com,*.onrender.com'
# Allow overriding via env var; remove empty entries
ALLOWED_HOSTS = [h for h in config('ALLOWED_HOSTS', default=default_hosts).split(',') if h]
# If Render provides the external hostname, include it automatically
render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME') or os.environ.get('RENDER_EXTERNAL_URL')
if render_hostname and render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_hostname)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tienda',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {}

# Prefer a DATABASE_URL environment variable (e.g. Supabase, Heroku style).
database_url = os.environ.get('DATABASE_URL') or os.environ.get('DATABASE_URL_INTERNAL')
if database_url:
    # Parse postgres URL: postgres://user:pass@host:port/dbname?sslmode=require
    parsed = urlparse(database_url)
    db_name = parsed.path.lstrip('/')
    db_user = parsed.username or ''
    db_password = parsed.password or ''
    db_host = parsed.hostname or ''
    db_port = parsed.port or ''

    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db_name,
        'USER': db_user,
        'PASSWORD': db_password,
        'HOST': db_host,
        'PORT': db_port,
    }

    # If sslmode is present in query, set OPTIONS
    query = parse_qs(parsed.query)
    sslmode = query.get('sslmode', [None])[0]
    if sslmode:
        DATABASES['default']['OPTIONS'] = {'sslmode': sslmode}
else:
    # Fallback to explicit env vars. Support both losgatosdb_* names and generic DB_* names.
    DATABASES['default'] = {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('losgatosdb_POSTGRES_DATABASE', default=config('DB_NAME', default='postgres')),
        'USER': config('losgatosdb_POSTGRES_USER', default=config('DB_USER', default='postgres')),
        'PASSWORD': config('losgatosdb_POSTGRES_PASSWORD', default=config('DB_PASSWORD', default='postgres')),
        'HOST': config('losgatosdb_POSTGRES_HOST', default=config('DB_HOST', default='localhost')),
        'PORT': config('losgatosdb_POSTGRES_PORT', default=config('DB_PORT', default='5432')),
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Read locale settings from environment so migrations and runtime use correct zone
LANGUAGE_CODE = config('LANGUAGE_CODE', default='es-CL')

# TIME_ZONE should match your project's locale (Render / Supabase examples use America/Santiago)
TIME_ZONE = config('TIME_ZONE', default='America/Santiago')

USE_I18N = True

# Use timezone-aware datetimes by default
USE_TZ = True

# Optional: persistent DB connections (seconds). 0 = disable persistent connections
CONN_MAX_AGE = config('CONN_MAX_AGE', default=0, cast=int)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Use CompressedStaticFilesStorage in production to avoid Manifest-related collectstatic failures
# If you later want fingerprinted filenames, switch back to CompressedManifestStaticFilesStorage
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "https://losgatosnegros-deploy-main.onrender.com",
    "http://localhost:3000",   # si usas frontend en localhost durante desarrollo
    "http://127.0.0.1:3000",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}